In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
# Importing the dataset
dataset = pd.read_csv('marks_3.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values

In [3]:
X

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int64)

In [4]:
y

array([ 8, 15, 30, 28, 58, 59, 78, 75], dtype=int64)

In [5]:
# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
regressor.intercept_

-4.392857142857146

In [7]:
regressor.coef_

array([10.72619048])

In [ ]:
# Predicting the Test set results
y_pred = regressor.predict(X)

In [ ]:
y_pred

In [ ]:
#model evaluation
rmse = mean_squared_error(y, y_pred)
r2 = r2_score(y, y_pred)

In [ ]:
r2

In [ ]:
y

In [ ]:
y_pred

In [ ]:
print('Slope:' ,regressor.coef_)
print('Intercept:', regressor.intercept_)

In [8]:
import statsmodels.api as sm

C:\Users\shrav\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
C:\Users\shrav\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:23: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  data_klasses = (pandas.Series, pandas.DataFrame, pandas.Panel)


In [9]:
X_lm = sm.add_constant(X)

# Create a first fitted model
lr = sm.OLS(y, X_lm).fit()


In [10]:
lr.params



array([-4.39285714, 10.72619048])

In [11]:
print(lr.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.943
Model:                            OLS   Adj. R-squared:                  0.933
Method:                 Least Squares   F-statistic:                     98.37
Date:                Sat, 26 Dec 2020   Prob (F-statistic):           6.07e-05
Time:                        20:37:04   Log-Likelihood:                -25.778
No. Observations:                   8   AIC:                             55.56
Df Residuals:                       6   BIC:                             55.71
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -4.3929      5.461     -0.804      0.4

C:\Users\shrav\Anaconda3\lib\site-packages\scipy\stats\stats.py:1604: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))
